<?php

/*********************************************************************
* Extension configuration file for ext "svconnector".
*
* Generated by ext 05-06-2014 06:23 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Connector Services',
  'description' => 'This family of services is used to connect to external data sources and fetch data from them. This is just a base class which cannot be used by itself. Implementations are done for specific subtypes.',
  'category' => 'services',
  'author' => 'Francois Suter (Cobweb)',
  'author_email' => 'typo3@cobweb.ch',
  'shy' => '',
  'dependencies' => '',
  'conflicts' => '',
  'priority' => '',
  'module' => 'mod1',
  'state' => 'stable',
  'internal' => '',
  'uploadfolder' => 0,
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 1,
  'lockType' => '',
  'author_company' => '',
  'version' => '2.4.0',
  'constraints' =>
  array (
    'depends' =>
    array (
		'typo3' => '6.2.0-7.99.99',
	),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
      'devlog' => '',
    ),
  ),
  'suggests' =>
  array (
  ),
  'comment' => 'Verified compatibility with TYPO3 CMS 6.2; fixed some small bugs; documentation moved to reStructuredText.',
  'user' => 'francois',
);

?>